const ShopActionTypes = {
  FETCH_DISHES_START: "FETCH_DISHES_START",
  FETCH_DISHES_SUCCESS: "FETCH_DISHES_SUCCESS",
  FETCH_DISHES_FAILURE: "FETCH_DISHES_FAILURE"
};

export default ShopActionTypes;
